workflows:
  android-workflow:
    name: Ionic Cordova Android Workflow
    max_build_duration: 120
    environment:
      android_signing:
        - keystore_reference
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "io.codemagic.ionicsample"
        GOOGLE_PLAY_TRACK: alpha
      node: latest
    scripts:
      - name: Install npm dependencies and update Cordova version
        script: | 
          npm install
          npm ci # equivalent of npm install for CI systems.
            # Requires package-lock.json or npm-shrinkwrap.json to be present
          cvm install 9.0.0
          cvm use 9.0.0 
      - name: Setup Cordova Android platform
        script: | 
          ionic cordova platform remove android --nosave
          ionic cordova platform add android \
            --confirm \
            --no-interactive \
            --noresources 
      - name: Build Android Cordova App
        script: | 
          ionic cordova build android \
            --release \
            --no-interactive \
            --prod \
            --device
      