workflows:
    sample-workflow:
        name: Codemagic Sample Workflow
        max_build_duration: 120
        instance_type: mac_mini_m1
scripts:
    - name: Install npm dependencies and update Cordova version
script: | 
      npm install
      npm ci # equivalent of npm install for CI systems.
              # Requires package-lock.json or npm-shrinkwrap.json to be present
      cvm install 9.0.0
      cvm use 9.0.0
      -  name: Setup Cordova  
      script: | 
        cordova platform add electron
        cordova build electron
          